on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub ì½”ë“œ ì²´í¬ì•„ì›ƒ
        uses: actions/checkout@v3

      - name: ì„œë²„ì— ì ‘ì† í›„ ìë™ ë°°í¬ (clone or pull)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ ! -d ~/Web_project ]; then
              echo "ğŸ”¹ í”„ë¡œì íŠ¸ í´ë” ì—†ìŒ â†’ git clone"
              git clone git@github.com:qoepwurity/Web_project.git ~/Web_project
            else
              echo "ğŸ”¹ í”„ë¡œì íŠ¸ í´ë” ìˆìŒ â†’ git pull"
              cd ~/Web_project
              git pull origin main
            fi

            cd ~/Web_project
            docker-compose down
            docker-compose up -d --build